# -*- coding: utf-8 -*-
"""Project-01_Kel-5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aYEjWXjc5pp_5NvL-ZXUjnZZ0QD1VJNx
"""

import numpy as np
import pandas as pd
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix, ConfusionMatrixDisplay
from sklearn import metrics

# Import Data
kelas = files.upload()
data = files.upload()

class_df = pd.read_csv('class.csv')
train_df = pd.read_csv('zoo.csv')

class_df.info()
train_df.info()

# Pengolahan Data
label ={1 : 'Mammal', 2 : 'Bird', 3 : 'Reptile', 4 : 'Fish', 5 : 'Amphibian', 6 : 'Bug', 7 : 'Invertebrate'}
x = train_df.iloc[:, 1:17].values
y = train_df.iloc[:, 17].values
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# Proses Training & Testing
classifier_svm = svm.SVC(kernel = 'linear')
classifier_svm.fit(x_train, y_train)
y_pred_svm = classifier_svm.predict(x_test)
print(f"Accuracy = {metrics.accuracy_score(y_test, y_pred_svm)}")
print(metrics.classification_report(y_test, y_pred_svm))

# Prediksi Kelas Dari Input Baru

# Contoh Input 1: Capybara
masbro = [1,0,0,1,0,0,0,1,1,1,0,0,4,1,1,1]
masbro = np.array(masbro).reshape(1, -1)
predicted_class_c = classifier_svm.predict(masbro)
masbro_label = label[predicted_class_c[0]]
print(f'Kelas Capybara: {masbro_label}')

# Contoh Input 2: Laba-laba
peterparker = [1,0,0,0,0,0,1,1,0,1,1,0,6,0,0,0]
peterparker = np.array(peterparker).reshape(1, -1)
predicted_class_p = classifier_svm.predict(peterparker)
peterparker_label = label[predicted_class_p[0]]
print(f'Kelas Laba-laba: {peterparker_label}')

# Contoh Input 3: Buaya
playboy = [0,0,1,0,0,1,1,1,1,1,0,0,4,1,1,1]
playboy = np.array(playboy).reshape(1, -1)
predicted_class_b = classifier_svm.predict(playboy)
playboy_label = label[predicted_class_b[0]]
print(f'Kelas Buaya: {playboy_label}')